remote_theme: coursweb/jk-theme
title: Lectures pédagogiques
description: Notes et résumés de lecture
lang: fr-FR
chapters:
# - title: Cours-web
#   url: https://cours-web.ch/
# - title: Bases en informatique
#   url: https://cours-web.ch/informatique-base/

   # Footer content
# Content is split in three columns.   
footer_col_1: <ul class="contact-list">
  <li>Manuel Schmalstieg</li>
  <li>2022</li></ul>
footer_col_2: <ul class="social-media-list"><li><a href="https://github.com/ms-studio/lectures-pedagogie">Lien Github</a></li></ul>